In [19]:
import torch
from einops import rearrange,einsum

t=torch.arange(10)
theta=10000.0

dim=5
d=torch.arange(0,dim,2)/dim
freqs=theta**-d
print(freqs)
freqs=einsum(t,freqs,"t,f->t f")
print(freqs[1])
cos, sin = torch.cos(freqs), torch.sin(freqs)
torch.stack((cos, sin))

tensor([1.0000e+00, 2.5119e-02, 6.3096e-04])
tensor([1.0000e+00, 2.5119e-02, 6.3096e-04])


tensor([[[ 1.0000e+00,  1.0000e+00,  1.0000e+00],
         [ 5.4030e-01,  9.9968e-01,  1.0000e+00],
         [-4.1615e-01,  9.9874e-01,  1.0000e+00],
         [-9.8999e-01,  9.9716e-01,  1.0000e+00],
         [-6.5364e-01,  9.9496e-01,  1.0000e+00],
         [ 2.8366e-01,  9.9212e-01,  1.0000e+00],
         [ 9.6017e-01,  9.8866e-01,  9.9999e-01],
         [ 7.5390e-01,  9.8458e-01,  9.9999e-01],
         [-1.4550e-01,  9.7988e-01,  9.9999e-01],
         [-9.1113e-01,  9.7455e-01,  9.9998e-01]],

        [[ 0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 8.4147e-01,  2.5116e-02,  6.3096e-04],
         [ 9.0930e-01,  5.0217e-02,  1.2619e-03],
         [ 1.4112e-01,  7.5285e-02,  1.8929e-03],
         [-7.5680e-01,  1.0031e-01,  2.5238e-03],
         [-9.5892e-01,  1.2526e-01,  3.1548e-03],
         [-2.7942e-01,  1.5014e-01,  3.7857e-03],
         [ 6.5699e-01,  1.7493e-01,  4.4167e-03],
         [ 9.8936e-01,  1.9960e-01,  5.0476e-03],
         [ 4.1212e-01,  2.2415e-01,  5.6786e-03]

In [25]:
import torch
import einx
a=torch.arange(4)
b=einx.rearrange('query -> query 1',a)
c=einx.rearrange('key -> 1 key',a)
b>=c

tensor([[ True, False, False, False],
        [ True,  True, False, False],
        [ True,  True,  True, False],
        [ True,  True,  True,  True]])

In [2]:
import torch
s = torch.tensor(0,dtype=torch.float32)
for i in range(1000): 
    s += torch.tensor(0.01,dtype=torch.float32) 
print(s)

tensor(10.0001)


In [3]:
s = torch.tensor(0,dtype=torch.float16) 
for i in range(1000): 
    s += torch.tensor(0.01,dtype=torch.float16) 
print(s)

tensor(9.9531, dtype=torch.float16)


In [4]:
s = torch.tensor(0,dtype=torch.float32) 
for i in range(1000): 
    s += torch.tensor(0.01,dtype=torch.float16) 
print(s)

tensor(10.0021)


In [5]:
s = torch.tensor(0,dtype=torch.float32) 
for i in range(1000): 
    x = torch.tensor(0.01,dtype=torch.float16) 
    s += x.type(torch.float32) 
print(s)

tensor(10.0021)


In [1]:
from basics.model import BasicTransformerLM
from basics.tokenizer import Tokenizer
import numpy as np
import torch

model=BasicTransformerLM.from_pretrained("data/out/checkpoints").to("mps")

vocab_path = 'data/tinystory/vocab.json' # 请替换为您的路径
merges_path = 'data/tinystory/merge.txt'  # 请替换为您的路径
special_tokens = ['<|endoftext|>'] # 示例特殊token

tokenizer = Tokenizer.from_files(
        vocab_filepath=vocab_path, 
        merges_filepath=merges_path, 
        special_tokens=special_tokens
    )


In [20]:
ids=tokenizer.encode("1")
ids=np.array(ids)
ids=torch.stack([
    torch.from_numpy(ids.astype(np.int64))
]).to("mps")
tokenizer.decode(model.generate(ids,30)[0].tolist())


' you can use to help me pick up get a fork. You can get my fork better. It is better to fall."\nBen was happy to'

In [25]:
y=torch.empty(2,4)
y.stride(1)
x=torch.empty(4,1)
print(x.stride(0))

1
